defaults:
  -
    scope:
        path: ""
        type: post
    values:
        layout: post
        author: John Cheesman

permalink: /:categories/:title/
name: John Cheesman
description: I'm a Front End Developer based in Derby who studied MA in Web Design and Content Planning. I Build fully responsive web sites and applications.
url: http://johncheesman.org.uk
highlighter: rouge
exclude: [node_modules]
